apiVersion: v1
kind: ConfigMap
metadata:
  name: auction-platform-config
  namespace: auction-platform
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  
  # Database
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  
  # Redis
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  
  # RabbitMQ
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  
  # Service URLs (internal)
  AUCTION_SERVICE_URL: "http://auction-api:80"
  BIDDING_SERVICE_URL: "http://bidding-api:80"
  PAYMENT_SERVICE_URL: "http://payment-api:80"
  NOTIFICATION_SERVICE_URL: "http://notification-api:80"
  STORAGE_SERVICE_URL: "http://storage-api:80"
  IDENTITY_SERVICE_URL: "http://identity-api:80"
  ANALYTICS_SERVICE_URL: "http://analytics-api:80"
