apiVersion: v1
kind: ServiceAccount
metadata:
  name: auction-service-account
  namespace: auction-platform
  labels:
    app.kubernetes.io/part-of: auction-platform
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: auction-service-role
  namespace: auction-platform
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["auction-platform-secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auction-service-rolebinding
  namespace: auction-platform
subjects:
  - kind: ServiceAccount
    name: auction-service-account
    namespace: auction-platform
roleRef:
  kind: Role
  name: auction-service-role
  apiGroup: rbac.authorization.k8s.io
